export default function PianoKeys ({handleEvent}) {
  return (
      <div className='keys'>

        <button className='key white' data-note='A-0' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A-0</span></button>
        <button className='key black' data-note='A#0' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A#0</span></button>
        <button className='key white' data-note='B-0' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>B-0</span></button>

        <button className='key white' data-note='C-1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C-1</span></button>
        <button className='key black' data-note='C#1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C#1</span></button>
        <button className='key white' data-note='D-1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D-1</span></button>
        <button className='key black' data-note='D#1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D#1</span></button>
        <button className='key white' data-note='E-1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>E-1</span></button>
        <button className='key white' data-note='F-1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F-1</span></button>
        <button className='key black' data-note='F#1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F#1</span></button>
        <button className='key white' data-note='G-1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G-1</span></button>
        <button className='key black' data-note='G#1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G#1</span></button>
        <button className='key white' data-note='A-1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A-1</span></button>
        <button className='key black' data-note='A#1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A#1</span></button>
        <button className='key white' data-note='B-1' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>B-1</span></button>

        <button className='key white' data-note='C-2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C-2</span></button>
        <button className='key black' data-note='C#2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C#2</span></button>
        <button className='key white' data-note='D-2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D-2</span></button>
        <button className='key black' data-note='D#2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D#2</span></button>
        <button className='key white' data-note='E-2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>E-2</span></button>
        <button className='key white' data-note='F-2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F-2</span></button>
        <button className='key black' data-note='F#2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F#2</span></button>
        <button className='key white' data-note='G-2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G-2</span></button>
        <button className='key black' data-note='G#2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G#2</span></button>
        <button className='key white' data-note='A-2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A-2</span></button>
        <button className='key black' data-note='A#2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A#2</span></button>
        <button className='key white' data-note='B-2' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>B-2</span></button>

        <button className='key white' data-note='C-3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C-3</span></button>
        <button className='key black' data-note='C#3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C#3</span></button>
        <button className='key white' data-note='D-3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D-3</span></button>
        <button className='key black' data-note='D#3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D#3</span></button>
        <button className='key white' data-note='E-3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>E-3</span></button>
        <button className='key white' data-note='F-3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F-3</span></button>
        <button className='key black' data-note='F#3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F#3</span></button>
        <button className='key white' data-note='G-3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G-3</span></button>
        <button className='key black' data-note='G#3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G#3</span></button>
        <button className='key white' data-note='A-3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A-3</span></button>
        <button className='key black' data-note='A#3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A#3</span></button>
        <button className='key white' data-note='B-3' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>B-3</span></button>

        <button className='key white' data-note='C-4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C-4</span></button>
        <button className='key black' data-note='C#4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C#4</span></button>
        <button className='key white' data-note='D-4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D-4</span></button>
        <button className='key black' data-note='D#4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D#4</span></button>
        <button className='key white' data-note='E-4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>E-4</span></button>
        <button className='key white' data-note='F-4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F-4</span></button>
        <button className='key black' data-note='F#4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F#4</span></button>
        <button className='key white' data-note='G-4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G-4</span></button>
        <button className='key black' data-note='G#4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G#4</span></button>
        <button className='key white' data-note='A-4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A-4</span></button>
        <button className='key black' data-note='A#4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A#4</span></button>
        <button className='key white' data-note='B-4' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>B-4</span></button>

        <button className='key white' data-note='C-5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C-5</span></button>
        <button className='key black' data-note='C#5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C#5</span></button>
        <button className='key white' data-note='D-5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D-5</span></button>
        <button className='key black' data-note='D#5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D#5</span></button>
        <button className='key white' data-note='E-5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>E-5</span></button>
        <button className='key white' data-note='F-5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F-5</span></button>
        <button className='key black' data-note='F#5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F#5</span></button>
        <button className='key white' data-note='G-5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G-5</span></button>
        <button className='key black' data-note='G#5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G#5</span></button>
        <button className='key white' data-note='A-5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A-5</span></button>
        <button className='key black' data-note='A#5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A#5</span></button>
        <button className='key white' data-note='B-5' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>B-5</span></button>

        <button className='key white' data-note='C-6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C-6</span></button>
        <button className='key black' data-note='C#6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C#6</span></button>
        <button className='key white' data-note='D-6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D-6</span></button>
        <button className='key black' data-note='D#6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D#6</span></button>
        <button className='key white' data-note='E-6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>E-6</span></button>
        <button className='key white' data-note='F-6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F-6</span></button>
        <button className='key black' data-note='F#6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F#6</span></button>
        <button className='key white' data-note='G-6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G-6</span></button>
        <button className='key black' data-note='G#6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G#6</span></button>
        <button className='key white' data-note='A-6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A-6</span></button>
        <button className='key black' data-note='A#6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A#6</span></button>
        <button className='key white' data-note='B-6' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>B-6</span></button>

        <button className='key white' data-note='C-7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C-7</span></button>
        <button className='key black' data-note='C#7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C#7</span></button>
        <button className='key white' data-note='D-7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D-7</span></button>
        <button className='key black' data-note='D#7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>D#7</span></button>
        <button className='key white' data-note='E-7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>E-7</span></button>
        <button className='key white' data-note='F-7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F-7</span></button>
        <button className='key black' data-note='F#7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>F#7</span></button>
        <button className='key white' data-note='G-7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G-7</span></button>
        <button className='key black' data-note='G#7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>G#7</span></button>
        <button className='key white' data-note='A-7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A-7</span></button>
        <button className='key black' data-note='A#7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>A#7</span></button>
        <button className='key white' data-note='B-7' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>B-7</span></button>

        <button className='key white' data-note='C-8' onMouseDown={(e)=>{handleEvent(e)}} onMouseUp={(e)=>{handleEvent(e)}} onMouseLeave={(e)=>{handleEvent(e)}} onTouchStart={(e)=>{handleEvent(e)}} onTouchEnd={(e)=>{handleEvent(e)}}><span>C-8</span></button>

    </div>
  )
}